// eslint-disable-next-line import/no-anonymous-default-export
export default [
    {
        id:1,
        checked:false,
        label:"SONY"
    },
    {
        id:2,
        checked:false,
        label:"ACER"
    },
    {
        id:3,
        checked:false,
        label:"ANITECH"
    },
    {
        id:4,
        checked:false,
        label:"ASUS"
    },
    {
        id:5,
        checked:"false",
        label:"BLACK SHARK"
    },
    {
        id:6,
        checked:false,
        label:"FANTECH"
    },
    {
        id:7,
        checked:false,
        label:"HUNTERSPIDER"
    },
    {
        id:8,
        checked:false,
        label:"HYPER X"
    },
    {
        id:9,
        checked:false,
        label:"LENOVO"
    },
    {
        id:10,
        checked:false,
        label:"LOGITECH"
    },
    {
        id:11,
        checked:false,
        label:"MEETION"
    },
    {
        id:12,
        checked:false,
        label:"MSI"
    },
    {
        id:13,
        checked:false,
        label:"NEOLUTION"
    },
    {
        id:14,
        checked:false,
        label:"NUBWO"
    },
    {
        id:15,
        checked:false,
        label:"ONIKUMA"
    },
    {
        id:16,
        checked:false,
        label:"RAZER"
    },
    {
        id:17,
        checked:false,
        label:"SIGNO"
    },
    {
        id:18,
        checked:false,
        label:"STEELSERIES"
    },
    {
        id:19,
        checked:false,
        label:"EPOS"
    },
    {
        id:20,
        checked:false,
        label:"HYPER"
    },
    {
        id:21,
        checked:false,
        label:"COOLER"
    },
    {
        id:22,
        checked:false,
        label:"EGA"
    },

    
];