# Generated by Django 4.0.3 on 2022-03-16 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyboard',
            old_name='KeyboardName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='mouse',
            old_name='MouseName',
            new_name='Name',
        ),
    ]
