# Generated by Django 4.0.2 on 2022-03-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_rename_keyboardname_keyboard_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadGear',
            fields=[
                ('HeadGearId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Brand', models.CharField(blank=True, max_length=500)),
                ('PictureLink', models.CharField(blank=True, max_length=500)),
                ('Banana', models.CharField(default='None', max_length=500)),
                ('PowerB', models.CharField(default='None', max_length=500)),
                ('Jib', models.CharField(default='None', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='keyboard',
            name='Banana',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='Brand',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='Jib',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='PictureLink',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='PowerB',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='mouse',
            name='Banana',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='mouse',
            name='Brand',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mouse',
            name='Jib',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='mouse',
            name='PictureLink',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mouse',
            name='PowerB',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
