# Generated by Django 4.0.3 on 2022-04-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0004_headgear_detail_keyboard_detail_mouse_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headgear',
            old_name='Jib',
            new_name='Ihavecpu',
        ),
        migrations.RenameField(
            model_name='keyboard',
            old_name='Jib',
            new_name='Ihavecpu',
        ),
        migrations.RenameField(
            model_name='mouse',
            old_name='Jib',
            new_name='Ihavecpu',
        ),
        migrations.RemoveField(
            model_name='headgear',
            name='PowerB',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='PowerB',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='PowerB',
        ),
    ]
