# Generated by Django 4.0.3 on 2022-04-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0004_headgear_detail_keyboard_detail_mouse_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headgear',
            name='Jib',
        ),
        migrations.RemoveField(
            model_name='headgear',
            name='PowerB',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='Jib',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='PowerB',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='Jib',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='PowerB',
        ),
        migrations.AddField(
            model_name='headgear',
            name='Ihavecpu',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='Ihavecpu',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AddField(
            model_name='mouse',
            name='Ihavecpu',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='headgear',
            name='Banana',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='headgear',
            name='Detail',
            field=models.CharField(default='ไม่มีข้อมูล', max_length=500),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='Banana',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='Detail',
            field=models.CharField(default='ไม่มีข้อมูล', max_length=500),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='Banana',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='Detail',
            field=models.CharField(default='ไม่มีข้อมูล', max_length=500),
        ),
    ]
