# Generated by Django 4.0.3 on 2022-04-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0005_rename_jib_headgear_ihavecpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headgear',
            name='Price',
            field=models.IntegerField(default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='Price',
            field=models.IntegerField(default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='mouse',
            name='Price',
            field=models.IntegerField(default='None', max_length=1000),
        ),
    ]
