# Generated by Django 4.0.3 on 2022-04-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0005_remove_headgear_jib_remove_headgear_powerb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headgear',
            name='RegularName',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='RegularName',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mouse',
            name='RegularName',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='Detail',
            field=models.CharField(default='ไม่มีข้อมูล', max_length=20000),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='Detail',
            field=models.CharField(default='ไม่มีข้อมูล', max_length=20000),
        ),
    ]
