# Generated by Django 4.0.3 on 2022-04-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0006_headgear_regularname_keyboard_regularname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headgear',
            name='Type',
            field=models.CharField(default='HeadGear', max_length=10),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='Type',
            field=models.CharField(default='Keyboard', max_length=10),
        ),
        migrations.AddField(
            model_name='mouse',
            name='Type',
            field=models.CharField(default='Mouse', max_length=10),
        ),
        migrations.AlterField(
            model_name='headgear',
            name='Detail',
            field=models.CharField(default='ไม่มีข้อมูล', max_length=30000),
        ),
    ]
