# Generated by Django 4.0.3 on 2022-04-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0006_headgear_price_keyboard_price_mouse_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headgear',
            name='Price',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='Price',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='Price',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
