# Generated by Django 4.0.3 on 2022-04-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0007_alter_headgear_price_alter_keyboard_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headgear',
            name='Banana',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='headgear',
            name='Ihavecpu',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='headgear',
            name='Price',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='Banana',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='Ihavecpu',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='Price',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='Banana',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='Ihavecpu',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='Price',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
